# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vish-azure-proj

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://vishazureprojacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d564e62a81ce416b8c5ede2e1ebe2f53 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_785d56a70e86457c9c4e774d207108ae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vishazureprojacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d564e62a81ce416b8c5ede2e1ebe2f53 }}/vishazureproj697d:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vish-azure-proj'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_82ff9da1dc78432893111823d6dd38c5 }}
        images: 'vishazureprojacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d564e62a81ce416b8c5ede2e1ebe2f53 }}/vishazureproj697d:${{ github.sha }}'